name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

strategy:
  matrix:
    otp: [21, 22, 23, 24]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: rebar3 compile
      - name: Run dialyzer
        run: rebar3 dialyzer
      - name: Run tests
        run: rebar3 eunit
